apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: chips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: flask-api:latest               # <-- image locale
        imagePullPolicy: IfNotPresent         # <-- ajout crucial
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: chipsdb

---
apiVersion: v1
kind: Service
metadata:
  name: flask-api
  namespace: chips
spec:
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
